cadastro_empresa/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from core.api.viewsets import EmpresaViewSet

router = routers.DefaultRouter()
router.register(r"empresas", EmpresaViewSet, basename="empresas")


urlpatterns = [
    path("", include("core.urls")),
    path("api/v1/", include(router.urls)),
    path("admin/", admin.site.urls),
]

core/urls.py
from django.urls import path
from core.views import (
    home,
    criar_empresa,
    atualizar_empresa,
    excluir_empresa,
    visualizar_empresa,
)

urlpatterns = [
    path("", home, name="home"),
    path("criar/", criar_empresa, name="criar_empresa"),
    path("vizualizar/<int:pk>", visualizar_empresa, name="visualizar_empresa"),
    path("editar/<int:pk>", atualizar_empresa, name="atualizar_empresa"),
    path("excluir/<int:pk>", excluir_empresa, name="excluir_empresa"),
]

core/models.py
from django.db import models
from django.core.validators import validate_email
from core.validators import valid_cnpj

# from core.validators import valid_date


class Empresa(models.Model):
    RISCOS = [
        ("AA", "AA"),
        ("A", "A"),
        ("B", "B"),
        ("C", "C"),
        ("D", "D"),
        ("E", "E"),
        ("F", "F"),
        ("G", "G"),
        ("H", "H"),
    ]

    STATUS = [("A", "Ativo"), ("I", "Inativo")]

    ESTADO = [
        ("AC", "AC"),
        ("AL", "AL"),
        ("AP", "AP"),
        ("AM", "AM"),
        ("BA", "BA"),
        ("CE", "CE"),
        ("ES", "ES"),
        ("GO", "GO"),
        ("MA", "MA"),
        ("MT", "MT"),
        ("MS", "MS"),
        ("MG", "MG"),
        ("PA", "PA"),
        ("PB", "PB"),
        ("PR", "PR"),
        ("PE", "PE"),
        ("PI", "PI"),
        ("RJ", "RJ"),
        ("RN", "RN"),
        ("RS", "RS"),
        ("RO", "RO"),
        ("RR", "RR"),
        ("SC", "SC"),
        ("SP", "SP"),
        ("SE", "SE"),
        ("TO", "TO"),
        ("DF", "DF"),
    ]

    razao_social = models.CharField(max_length=200, blank=False)
    nome_fantasia = models.CharField(max_length=200, blank=True)
    cnpj = models.CharField(max_length=19, blank=False, validators=[valid_cnpj])
    email = models.EmailField(blank=True, validators=[validate_email])
    endereco = models.CharField(max_length=100, blank=True, null=True)
    cidade = models.CharField(max_length=20, blank=True)
    estado = models.CharField(max_length=2, choices=ESTADO, blank=True)
    telefone = models.CharField(max_length=15, blank=True)
    data_cadastro = models.DateField()
    status = models.CharField(max_length=6, choices=STATUS, blank=True)
    risco = models.CharField(max_length=2, choices=RISCOS, blank=True)
    agencia = models.CharField(max_length=6, blank=True)
    conta = models.CharField(max_length=10, blank=True)

    def __str__(self):
        return self.nome_fantasia

    class Meta:
        ordering = ["-nome_fantasia"]

core/forms.py
from django.forms import ModelForm
from core.models import Empresa


class CriarEmpresaForm(ModelForm):
    class Meta:
        model = Empresa
        fields = [
            "razao_social",
            "nome_fantasia",
            "cnpj",
            "email",
            "endereco",
            "cidade",
            "estado",
            "telefone",
            "data_cadastro",
            "status",
            "risco",
            "agencia",
            "conta",
        ]

core/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render

from core.models import Empresa

from .forms import CriarEmpresaForm


def home(request):
    empresas = Empresa.objects.all()
    return render(request, "index.html", {"empresas": empresas})


def criar_empresa(request):
    form = CriarEmpresaForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, "Empresa criada com sucesso.")
        return redirect("home")

    context = {"form": form}

    return render(request, "create.html", context)


def visualizar_empresa(request, pk):
    empresa = get_object_or_404(Empresa, pk=pk)
    return render(request, "visualizar.html", {"empresa": empresa})


def atualizar_empresa(request, pk):
    empresa = get_object_or_404(Empresa, pk=pk)
    if request.method == "POST":
        form = CriarEmpresaForm(data=request.POST, instance=empresa)
        if form.is_valid():
            form.save()
            messages.success(request, "Empresa atualizada com sucesso.")
            return redirect("home")
    else:
        form = CriarEmpresaForm(instance=empresa)

    return render(request, "update.html", {"form": form})


def excluir_empresa(request, pk):
    empresa = get_object_or_404(Empresa, pk=pk)
    empresa.delete()
    messages.success(request, "Empresa excluída com sucesso.")
    return redirect("home")

core/templates/base.html
{% load static %}   
<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
		<title>{% block title %}{% endblock %}</title>

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

	</head>
	<body>
		<nav class="navbar navbar-default" role="navigation">
			<div class="container">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'home' %}">Empresas</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="nav navbar-nav">
						<li><a href="{% url 'home' %}">Home</a></li>
						<li><a href="{% url 'criar_empresa' %}">Cria empresa</a></li>
					</ul>
				</div><!-- /.navbar-collapse -->
			</div>
		</nav>
		{% if messages %}
			{% for message in messages %}
			<div class="alert alert-success text-center base-alert">
				{{ message }}
			</div>
			{% endfor %}
		{% endif %}
		<div class="container">
			<div class="top">
				{% block main %}
				{% endblock %}
			</div>
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/brazilian-values"></script>
		<script src="{% static 'js/script.js' %}"></script>
	</body>
</html>

core/templates/create.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block title %} Criar Empresa {% endblock %}

{% block main %}
<div class="row">
	<div class="col-lg-8 col-lg-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
					<h3 class="panel-title">Criar uma nova empresa</h3>
			</div>
					
			<form method="POST">
					{% csrf_token %}
					{{ form.non_field_errors }}
				<div class="panel-body">
					<div class="row">
						<div class="col-lg-12">
							<div class="form-group">
								<label for="razao_social">Razão Social</label>
								{{ form.razao_social.errors }}
								{% render_field form.razao_social class="form-control" %}
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-lg-6">
							<div class="form-group">
								<label for="nome_fantasia">Nome Fantasia</label>
								{% render_field form.nome_fantasia class="form-control" %}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label for="cnpj">CNPJ</label>
								{% render_field form.cnpj class="form-control" data-js="cnpj" %}
								{{ form.cnpj.errors }}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label for="email">Email</label>
								{% render_field form.email class="form-control" %}
								{{ form.email.errors }}
								
							</div>
							{{ form.email.errors }}
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label for="endereco">Endereço</label>
								{% render_field form.endereco class="form-control" %}

							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label for="cidade">Cidade</label>
								{% render_field form.cidade class="form-control" %}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label for="estato">Estado</label>
								{% render_field form.estado class="form-control" %}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label for="telefone">Telefone</label>
								{% render_field form.telefone class="form-control" data-js="telefone" %}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label for="data_cadastro">Data cadastro</label>
								{% render_field form.data_cadastro type="date" class="form-control" data-js="data" %}
								{{ form.data_cadastro.errors }}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label for="status">Status</label>
								{% render_field form.status class="form-control" %}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label for="risco">Risco</label>
								{% render_field form.risco class="form-control" %}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label for="agencia">Agencia</label>
								{% render_field form.agencia class="form-control" data-js="agencia" %}
							</div>
						</div>
						<div class="col-lg-6">
							<div class="form-group">
								<label for="conta">Conta</label>
								{% render_field form.conta class="form-control" data-js="conta" %}
							</div>
						</div>	
					</div>

					<div class="row">
						<hr />
						<div class="col-lg-6">
							<button type="submit" class="btn btn-info">Criar</button>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}

{% block title %}Empresas{% endblock %}

{% block main %}

	<div class="row">
			<div class="col-lg-8 col-lg-offset-2">
					<div class="panel panel-default">
							<div class="panel-heading">
									<h3 class="panel-title">Empresas</h3>
							</div>
									
							<ul class="list-group">
									{% if empresas %}
									{% for empresa in empresas %}
									<li class="list-group-item">
											<a href="{% url 'visualizar_empresa' empresa.id %}"><strong>{{ empresa.razao_social }}</strong></a>
											<span class="pull-right">
													<a href="{% url 'visualizar_empresa' empresa.id %}" class="btn btn-info btn-xs">Ver</a> &nbsp;
													<a href="{% url 'atualizar_empresa' empresa.id %}" class="btn btn-info btn-xs">Editar</a> &nbsp;
													<a href="{% url 'excluir_empresa' empresa.id %}" class="btn btn-danger btn-xs">Deletar</a> &nbsp;
											</span>
									</li>
									{% endfor %}
									{% else %}
									<li class="list-group-item text-center">
										Não há empresas cadastradas. <a href="{% url 'criar_empresa' %}">Clique aqui para criar uma.</a>
									</li>
									{% endif %}
							</ul>

					</div>
			</div>
	</div>
{% endblock %}

core/templates/update.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %} Atualizar Empresa {% endblock %}

{% block main %}
<div class="row">
	<div class="col-lg-8 col-lg-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
					<h3 class="panel-title">Atualizar empresa</h3>
			</div>
					
			<form method="POST">
					{% csrf_token %}
				<div class="panel-body">
					<div class="row">
						<div class="col-lg-12">
							<div class="form-group">
								<label for="id_razao_social">Razão Social</label>
								{% render_field form.razao_social class="form-control" %}
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-lg-4">
							<div class="form-group">
								<label for="id_nome_fantasia">Nome Fantasia</label>
								{% render_field form.nome_fantasia class="form-control" %}
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="id_cnpj">CNPJ</label>
								{% render_field form.cnpj class="form-control" data-js="cnpj" %}
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="id_email">Email</label>
								{% render_field form.email class="form-control" %}
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="id_endereco">Endereço</label>
								{% render_field form.endereco class="form-control" %}
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="id_cidade">Cidade</label>
								{% render_field form.cidade class="form-control" %}
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="id_estato">Estado</label>
								{% render_field form.estado class="form-control" %}
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="id_telefone">Telefone</label>
								{% render_field form.telefone class="form-control" data-js="telefone" %}
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="id_data_cadastro">Data cadastro</label>
								{% render_field form.data_cadastro type="date" class="form-control"%}
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="id_status">Status</label>
								{% render_field form.status class="form-control" %}
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="id_risco">Risco</label>
								{% render_field form.risco class="form-control" %}
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="id_agencia">Agencia</label>
								{% render_field form.agencia class="form-control" data-js="agencia" %}
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
								<label for="id_conta">Conta</label>
								{% render_field form.conta class="form-control" data-js="conta" %}
							</div>
						</div>
					</div>

					<div class="row">
						<hr />
						<div class="col-lg-4">
							<button type="submit" class="btn btn-info">Atualizar</button>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

core/templates/visualizar.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %} Empresa {% endblock %}

{% block main %}
<div class="row">
	<div class="col-lg-8 col-lg-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
					<h3 class="panel-title">Empresa</h3>
			</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-lg-12">
							<div class="form-group">
								<label for="razao_social">Razão Social</label>
								<input type="text" class="form-control" disabled value="{{ empresa.razao_social }}">
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-lg-4">
							<div class="form-group">
                                <label for="nome_fantasia">Nome Fantasia</label>
                                <input type="text" class="form-control" disabled value="{{ empresa.nome_fantasia }}">
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
                                <label for="cnpj">CNPJ</label>
                                <input type="text" class="form-control" disabled value="{{ empresa.cnpj }}">
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
                                <label for="email">Email</label>
                                <input type="text" class="form-control" disabled value="{{ empresa.email }}">
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
                                <label for="endereco">Endereço</label>
                                <input type="text" class="form-control" disabled value="{{ empresa.endereco }}">
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
                                <label for="cidade">Cidade</label>
                                <input type="text" class="form-control" disabled value="{{ empresa.cidade }}">
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
                                <label for="estato">Estado</label>
                                <input type="text" class="form-control" disabled value="{{ empresa.estado }}">
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
                                <label for="telefone">Telefone</label>
                                <input type="text" class="form-control" disabled value="{{ empresa.telefone }}">
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
                                <label for="data_cadastro">Data cadastro</label>
                                <input type="text" class="form-control" disabled value="{{ empresa.data_cadastro }}">
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
                                <label for="risco">Status</label>
                                <input type="text" class="form-control" disabled {% if empresa.status %}value="Ativa"{% else %}value="Não ativa"{% endif%}>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
                                <label for="risco">Risco</label>
                                <input type="text" class="form-control" disabled value="{{ empresa.risco }}">
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
                                <label for="agencia">Agencia</label>
                                <input type="text" class="form-control" disabled value="{{ empresa.agencia }}">
							</div>
						</div>
						<div class="col-lg-4">
							<div class="form-group">
                                <label for="conta">Conta</label>
                                <input type="text" class="form-control" disabled value="{{ empresa.conta }}">
							</div>
						</div>
					</div>

					<div class="row">
						<hr />
						<div class="col-lg-4">
                                <a href="{% url 'home' %}"><button class="btn btn-warning">Voltar</button></a>
                                <a href="{% url 'atualizar_empresa' empresa.id %}"><button class="btn btn-info">Atualizer</button></a>
                                <a href="{% url 'excluir_empresa' empresa.id %}"><button class="btn btn-danger">Excluir</button></a>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}